### ISSUE TITLE
Risc-V Soft Core List needs a better NanoV short description. 

### ISSUE THREAD

**Issue by PythonLinks** [MichaelBell/nanoV#1]
Using a circular shift for the registers is a great idea.  

So I added this RISC-V soft core to the list of RISC-V Soft Cores. 
https://github.com/PythonLinks/risc-v-shoot-out

The problem is that the blurb does not really describe the abstract idea. 
i did not quite get what you are doing.  Say there is a 32 bit word of data in ram. 
Is 1 bit for every register, then you circulate through all 32 bits?  Is that correct?
So why are 2 bits accessible at any time?

It would also be most helpful to list your LUTs used.  The other tiny two processors, SERVE and do list their LUTs used on their pages.

**Comment by MichaelBell** [comment]
Oof, I should update the Readme. “Currently in development” is very much not true any more 🤣

I don’t really intend to do much more with nanoV. It’s interesting that it fits in 2 Tiny Tapeout tiles, but it’s not particularly well written or easy to extend.

**Comment by PythonLinks** [comment]
If I understood it correctly, I think it is a great idea, and should definitely be mentioned. Others may build on it.   Maybe someone will build one optimized for FPGAs. 

You did mention 32 clocks for one cycle.  All 3 of these tiny soft cores need a way o compare their effective speed.  I am not sure what it is. 

And LUT count is very important to me.

**Comment by PythonLinks** [comment]
So I should add something like,  "For ASIC prototyping on FPGA's it uses shift registers.  An older version used BRAMs. LUT requirements of the older version are no longer available. "

**Comment by MichaelBell** [comment]
I've updated the readme of this project to help reflect the current state.  That description sounds reasonable, but honestly I'm not sure nanoV is a project worth highlighting on your page.

Possibly TinyQV could be of interest for that page, but again it's not a good choice for FPGA, and in its current form isn't amazing for "normal" ASIC applications either where constraints other than area are a concern, although that would potentially be fairly easily fixable.  FazyRV probably fills the same niche in a more general and well supported way.

**Comment by PythonLinks** [comment]
Thank you. 
Still the idea is so interest, I am keeping it. 
I also added Tiny-QV. 

Christopher Lozinski
@***@***.***
